# Generated by Django 5.2.5 on 2025-09-03 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='DFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Deal Finder User',
                'verbose_name_plural': 'Deal Finder Users',
                'db_table': 'df_user',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('internal_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('deal_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('game_id', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('steam_rating_text', models.CharField(blank=True, max_length=255)),
                ('steam_rating_percent', models.IntegerField(blank=True, null=True)),
                ('steam_rating_count', models.IntegerField(blank=True, null=True)),
                ('steam_app_id', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('last_change', models.DateTimeField(blank=True, null=True)),
                ('deal_rating', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('thumb', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='app.store')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deals',
                'ordering': ['-deal_rating', 'sale_price'],
            },
        ),
    ]
