# Generated by Django 5.2.5 on 2025-09-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='images',
        ),
    ]
