# Generated by Django 5.2.5 on 2025-09-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_store_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='internal_name',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='steam_app_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='steam_rating_count',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='steam_rating_percent',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='steam_rating_text',
        ),
    ]
