# Generated by Django 5.2.5 on 2025-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_deal_game_id_remove_deal_internal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='store_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
