# Generated by Django 5.2.6 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deal_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='steam_app_ID',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='steam_rating_text',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
