# Generated by Django 5.2.6 on 2025-09-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deal_steam_app_id_deal_steam_rating_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='steam_app_ID',
            new_name='steam_app_id',
        ),
    ]
