# Generated by Django 5.2.6 on 2025-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_steam_app_id_deal_steam_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='steam_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
