# Generated by Django 5.2.6 on 2025-09-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_deal_steam_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='steam_rating_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
